name: surf_practice_chat_flutter
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  mwwm: ^2.0.0
  surf_injector: ^1.0.0
  surf_util: ^1.0.3
  geolocator: ^8.2.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  flutter_svg: ^1.0.3
  relation: ^3.1.0

dev_dependencies:
  fake_async: ^1.2.0
  flutter_native_splash: ^2.0.2
  surf_lint_rules: ^1.4.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/